name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/)
    required: true

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}

outputs:
  triggered:
    description: 'Boolean result of triggers'
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Check if a build is required (steps.build.outputs.triggered=true|false)
    - uses: actions/checkout@v4
    - name: Diff for changes
      shell: bash
      id: diff
      run: |
        # Build if changed files (git diff) match triggers
        TRIGGERS=${{ inputs.triggers }}
        git fetch origin ${{ inputs.diff_branch }}
        while read -r check; do
          for t in "${TRIGGERS[@]}"; do
            if [[ "${check}" =~ "${t}" ]]; then
                # Output triggered=true for next steps
                echo "Build triggered based on git diff"
                echo -e "${t}\n --> ${check}"
                echo "triggered=true" >> $GITHUB_OUTPUT
                exit 0
            fi
          done
        done < <(git diff origin/${{ inputs.diff_branch }} --name-only)

        # If at this point, no trigger has fired
        echo "Container build not required"
        echo "triggered=false" >> $GITHUB_OUTPUT
