name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    outputs:
      triggered: ${{ steps.test.outputs.triggered }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: test
        with:
          triggers: ('.github/workflows/' 'action.yml')

  results:
    name: Results
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "Trigger result: ${{ needs.test.outputs.triggered }}"
